# import libraries
from PyQt5 import QtWidgets, QtCore, QtGui
from gui_methods import GUIMethods
from gui_gis import GUI_geofiles

# Main Class
class GUIInterface(QtWidgets.QMainWindow):
    
    def __init__(self):
        super().__init__()
        self.setupUi(self)
        self.methods = GUIMethods(self)  # Pass the UI to the methods class
        self.geo_qgis = GUI_geofiles(self)  # Pass the UI to the methods class
        """ Methods applied with button and others elements """
        
        # Selection of the project folder for saving data
        self.path_out_folder_bt.clicked.connect(self.methods.select_folder)
        
        self.method_button.clicked.connect(self.methods.select_insp_method)
        
        # Excute a emergent window to upload coordinates of the analysis area
        self.set_cood_button.clicked.connect(self.methods.open_emergent_window)
        
        # Normalize input data
        self.next_button.clicked.connect(self.geo_qgis.normalize_input)
        
        # Create a *.csv file "Country_City_building_info.csv" with its OSM ID and its coordinates
        self.next_button.clicked.connect(self.methods.create_database)
        
        # Create a *.csv file "Country_City_building_info.csv" with its OSM ID and its coordinates
        self.next_button.clicked.connect(self.methods.load_existing_insp)
                                         
        # Counts the ID of the images
        self.next_button.clicked.connect(self.methods.count_clicks_next)
        self.previous_button.clicked.connect(self.methods.count_clicks_previous)
        
        # Sets lat and lot values
        self.next_button.clicked.connect(self.methods.coordinates)
        self.previous_button.clicked.connect(self.methods.coordinates)
        
        # Gets the image from Google Street View
        self.next_button.clicked.connect(self.methods.fetch_three_step_views)
        self.previous_button.clicked.connect(self.methods.fetch_three_step_views)
        
        # Excutes a object detector model and trim the isolated building
        self.next_button.clicked.connect(self.methods.object_detector_building)
        self.previous_button.clicked.connect(self.methods.object_detector_building)
        
        # Create a manual bounding box
        self.bounding_box_1.clicked.connect(self.methods.bounding_box_frame_left)
        self.bounding_box_2.clicked.connect(self.methods.bounding_box_frame_central)
        self.bounding_box_3.clicked.connect(self.methods.bounding_box_frame_right)
        self.bounding_box_1.clicked.connect(self.methods.bounding_box)
        self.bounding_box_2.clicked.connect(self.methods.bounding_box)
        self.bounding_box_3.clicked.connect(self.methods.bounding_box)
        
        # Save the values of the inspections
        self.save_data_button.clicked.connect(self.methods.save_database)
        
        # Clean the values of the previous inspections
        self.next_button.clicked.connect(self.methods.clean_database)
        self.previous_button.clicked.connect(self.methods.clean_database)
        
        # Loads and excute a deep learning model for LLRS feature prediction
        self.next_button.clicked.connect(self.methods.material_prediction)
        self.next_button.clicked.connect(self.methods.llrs_prediction)
        self.next_button.clicked.connect(self.methods.code_level_prediction)
        self.next_button.clicked.connect(self.methods.n_stories_prediction)
        self.next_button.clicked.connect(self.methods.occupancy_prediction)
        self.next_button.clicked.connect(self.methods.block_position_prediction)
        
        # Search existing inspections
        self.search_img_button.clicked.connect(self.methods.search_inspection)
        self.search_img_button.clicked.connect(self.methods.coordinates)
        self.search_img_button.clicked.connect(self.methods.fetch_three_step_views)
        self.search_img_button.clicked.connect(self.methods.object_detector_building)
        self.search_img_button.clicked.connect(self.methods.clean_database)
        
    # Method which close the GUI in the console     
    def closeEvent(self, event):
        """Handle the default close button (X) event with a confirmation dialog."""
        # Create the QMessageBox dialog
        msgBox = QtWidgets.QMessageBox(self)
        msgBox.setIcon(QtWidgets.QMessageBox.Warning)
        msgBox.setWindowTitle("Confirmation")
        msgBox.setText("Have you saved your results?")
        msgBox.setInformativeText("Do you want to close the application?")
        
        # Add buttons for Yes and No
        yes_button = msgBox.addButton("Yes", QtWidgets.QMessageBox.YesRole)
        msgBox.addButton("No", QtWidgets.QMessageBox.NoRole)
    
        # Execute the QMessageBox and wait for user response
        msgBox.exec()
    
        # Handle the response
        if msgBox.clickedButton() == yes_button:
            # User confirmed, close the application
            print("GUI is closing...")
            QtWidgets.QApplication.quit()  # This will terminate the GUI and allow the script to continue
            print("------------- Thanks you ------------")
        else:
            # User canceled, do not close
            print("User canceled the close operation.")
            event.ignore()  # Prevent the GUI from closing

    
    # Definition of the different pluggin, button, among others (objects) of the GUI
    def setupUi(self, GUIInterface):
        
        """Set up the user interface components."""
        # Configure main window properties
        GUIInterface.setObjectName("GUIInterface")
        GUIInterface.resize(1570, 889)  # Size of the GUI (Display resolution)
        
        # Create a central widget where other widgets will be added
        self.centralwidget = QtWidgets.QWidget(GUIInterface)
        self.centralwidget.setObjectName("centralwidget")
        
        
        """ GUI Tittle elements """
        # Tittle of the GUI
        self.Tittle = QtWidgets.QLabel(self.centralwidget)
        self.Tittle.setGeometry(QtCore.QRect(550, 0, 441, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.Tittle.setFont(font)
        self.Tittle.setAlignment(QtCore.Qt.AlignCenter)
        self.Tittle.setObjectName("Tittle")
        
        
        """ Project folder elements """
        # Button for selecting the project folder
        self.path_out_folder_bt = QtWidgets.QPushButton(self.centralwidget)
        self.path_out_folder_bt.setGeometry(QtCore.QRect(1090, 90, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.path_out_folder_bt.setFont(font)
        self.path_out_folder_bt.setObjectName("path_out_folder_bt")
        # Project folder text value
        self.output_folder_value = QtWidgets.QLabel(self.centralwidget)
        self.output_folder_value.setGeometry(QtCore.QRect(1240, 90, 311, 31))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.output_folder_value.setFont(font)
        self.output_folder_value.setObjectName("output_folder_value")
        # Label of project selection
        self.output_path_tittle = QtWidgets.QLabel(self.centralwidget)
        self.output_path_tittle.setGeometry(QtCore.QRect(1090, 50, 181, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.output_path_tittle.setFont(font)
        self.output_path_tittle.setObjectName("output_path_tittle")
        
        
        """ Coordinates data elements"""
        # Label of latitude 
        self.lat_label = QtWidgets.QLabel(self.centralwidget)
        self.lat_label.setGeometry(QtCore.QRect(660, 50, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.lat_label.setFont(font)
        self.lat_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lat_label.setObjectName("lat_label")
        # Latitude value
        self.lat_value = QtWidgets.QLabel(self.centralwidget)
        self.lat_value.setGeometry(QtCore.QRect(840, 50, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lat_value.setFont(font)
        self.lat_value.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lat_value.setFrameShape(QtWidgets.QFrame.Box)
        self.lat_value.setObjectName("lat_value")
        
        # Label of longitude
        self.lon_label = QtWidgets.QLabel(self.centralwidget)
        self.lon_label.setGeometry(QtCore.QRect(660, 90, 171, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.lon_label.setFont(font)
        self.lon_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lon_label.setObjectName("lon_label")
        # Longitude value
        self.lon_value = QtWidgets.QLabel(self.centralwidget)
        self.lon_value.setGeometry(QtCore.QRect(840, 90, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lon_value.setFont(font)
        self.lon_value.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lon_value.setFrameShape(QtWidgets.QFrame.Box)
        self.lon_value.setObjectName("lon_value")
        
        
        """ Country and city elements"""
        # Label for the country 
        self.country_label_input = QtWidgets.QLabel(self.centralwidget)
        self.country_label_input.setGeometry(QtCore.QRect(20, 90, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.country_label_input.setFont(font)
        self.country_label_input.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.country_label_input.setObjectName("country_label_input")
        # Country value
        self.country_value = QtWidgets.QLabel(self.centralwidget)
        self.country_value.setGeometry(QtCore.QRect(110, 90, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.country_value.setFont(font)
        self.country_value.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.country_value.setFrameShape(QtWidgets.QFrame.Box)
        self.country_value.setObjectName("country_value")
        
        # Label for the city
        self.city_label = QtWidgets.QLabel(self.centralwidget)
        self.city_label.setGeometry(QtCore.QRect(270, 90, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.city_label.setFont(font)
        self.city_label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.city_label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.city_label.setObjectName("city_label")
        # City value
        self.city_value = QtWidgets.QLabel(self.centralwidget)
        self.city_value.setGeometry(QtCore.QRect(320, 90, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.city_value.setFont(font)
        self.city_value.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.city_value.setFrameShape(QtWidgets.QFrame.Box)
        self.city_value.setObjectName("city_value")
        
        # Colored frame area
        self.frame_location = QtWidgets.QFrame(self.centralwidget)
        self.frame_location.setGeometry(QtCore.QRect(10, 40, 631, 91))
        self.frame_location.setStyleSheet("background-color: rgb(254, 255, 174);")
        self.frame_location.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_location.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_location.setObjectName("frame_location")
        # Location label
        self.location_label = QtWidgets.QLabel(self.frame_location)
        self.location_label.setGeometry(QtCore.QRect(260, 10, 111, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.location_label.setFont(font)
        self.location_label.setAlignment(QtCore.Qt.AlignCenter)
        self.location_label.setObjectName("location_label")
        
        
        """ Button for next and previous building image"""
        # Button to get the next building images
        self.next_button = QtWidgets.QPushButton(self.centralwidget)
        self.next_button.setGeometry(QtCore.QRect(210, 820, 151, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.next_button.setFont(font)
        self.next_button.setObjectName("next_button")
        
        # Button to get the previous building images
        self.previous_button = QtWidgets.QPushButton(self.centralwidget)
        self.previous_button.setGeometry(QtCore.QRect(20, 820, 171, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.previous_button.setFont(font)
        self.previous_button.setObjectName("previous_button")
        
        # Colored area for next and previous button
        self.img_area = QtWidgets.QLabel(self.centralwidget)
        self.img_area.setGeometry(QtCore.QRect(10, 810, 371, 61))
        self.img_area.setStyleSheet("background-color: rgb(209, 170, 255);")
        self.img_area.setText("")
        self.img_area.setObjectName("img_area")
        self.img_area.raise_()
        
        
        """ Left Building images elements """
        # Left image color frame
        self.frame_left_img = QtWidgets.QFrame(self.centralwidget)
        self.frame_left_img.setGeometry(QtCore.QRect(10, 150, 511, 641))
        self.frame_left_img.setStyleSheet("background-color: rgb(102, 220, 255);")
        self.frame_left_img.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_left_img.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_left_img.setObjectName("frame_left_img")
        self.img_id_label_1 = QtWidgets.QLabel(self.frame_left_img)
        self.img_id_label_1.setGeometry(QtCore.QRect(10, 10, 111, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        # Elements for display left image or error message
        self.img_id_label_1.setFont(font)
        self.img_id_label_1.setAlignment(QtCore.Qt.AlignCenter)
        self.img_id_label_1.setObjectName("img_id_label_1")
        # Left image widget for best performance
        self.verticalLayoutWidget_5 = QtWidgets.QWidget(self.frame_left_img)
        self.verticalLayoutWidget_5.setGeometry(QtCore.QRect(10, 40, 491, 311))
        self.verticalLayoutWidget_5.setObjectName("verticalLayoutWidget_5")
        # Left image bounding box
        self.left_gsv_bb = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_5)
        self.left_gsv_bb.setContentsMargins(0, 0, 0, 0)
        self.left_gsv_bb.setObjectName("left_gsv_bb")
        # Left building image
        self.left_gsv_img = QtWidgets.QLabel(self.verticalLayoutWidget_5)
        self.left_gsv_img.setText("")
        self.left_gsv_img.setObjectName("left_gsv_img")
        self.left_gsv_bb.addWidget(self.left_gsv_img)
        # Image ID for left frame
        self.img_id_value_1 = QtWidgets.QLineEdit(self.frame_left_img)
        self.img_id_value_1.setGeometry(QtCore.QRect(130, 10, 111, 21))
        self.img_id_value_1.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.img_id_value_1.setObjectName("img_id_value_1")
        # Bounding box for image left frame
        self.bounding_box_1 = QtWidgets.QPushButton(self.centralwidget)
        self.bounding_box_1.setGeometry(QtCore.QRect(310, 160, 161, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.bounding_box_1.setFont(font)
        self.bounding_box_1.setObjectName("bounding_box_1")
        
        ################## Form for building feature ##########################
        
        # Material for left image label
        self.material_1 = QtWidgets.QLabel(self.centralwidget)
        self.material_1.setGeometry(QtCore.QRect(20, 510, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.material_1.setFont(font)
        self.material_1.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.material_1.setObjectName("material_1")
        # Material Combobox elements
        self.material_cb_1 = QtWidgets.QComboBox(self.centralwidget)
        self.material_cb_1.setGeometry(QtCore.QRect(170, 510, 241, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.material_cb_1.setFont(font)
        self.material_cb_1.setObjectName("material_cb_1")
        self.material_cb_1.addItem("Select Material")
        self.material_cb_1.addItem("Adobe-Earth-Stone","AES")
        self.material_cb_1.addItem("Concrete", "CR")
        self.material_cb_1.addItem("Masonry - Confined","MCF")
        self.material_cb_1.addItem("Masonry - Reinforced","MR")
        self.material_cb_1.addItem("Masonry - Unreinforced","MUR")
        self.material_cb_1.addItem("Steel","S")
        self.material_cb_1.addItem("Other","MATO")
        self.material_cb_1.setCurrentIndex(0)
        self.material_cb_1.view().setFixedWidth(250)
        
        # LLRS for left image label
        self.llrs_1 = QtWidgets.QLabel(self.centralwidget)
        self.llrs_1.setGeometry(QtCore.QRect(20, 549, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.llrs_1.setFont(font)
        self.llrs_1.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.llrs_1.setObjectName("llrs_1")
        # LLRS Combobox elements
        self.llrs_cb_1 = QtWidgets.QComboBox(self.centralwidget)
        self.llrs_cb_1.setGeometry(QtCore.QRect(170, 551, 241, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.llrs_cb_1.setFont(font)
        self.llrs_cb_1.setObjectName("llrs_cb_1")
        self.llrs_cb_1.addItem("Select LLRS")
        self.llrs_cb_1.addItem("Dual System","LDUAL")
        self.llrs_cb_1.addItem("Infilled Frames", "LFINF")
        self.llrs_cb_1.addItem("Moment Frames", "LFM")
        self.llrs_cb_1.addItem("Walls","LWAL")
        self.llrs_cb_1.addItem("Thin Wall","TW")
        self.llrs_cb_1.addItem("Other","O")
        self.llrs_cb_1.setCurrentIndex(0)
        self.llrs_cb_1.view().setFixedWidth(250)
        
        # Code level for left image label
        self.age_1 = QtWidgets.QLabel(self.centralwidget)
        self.age_1.setGeometry(QtCore.QRect(20, 590, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.age_1.setFont(font)
        self.age_1.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.age_1.setObjectName("age_1")
        # Code level Combobox elements
        self.age_cb_1 = QtWidgets.QComboBox(self.centralwidget)
        self.age_cb_1.setGeometry(QtCore.QRect(170, 590, 241, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.age_cb_1.setFont(font)
        self.age_cb_1.setObjectName("age_cb_1")
        self.age_cb_1.addItem("Select Code Level")
        self.age_cb_1.addItem("High-Code","HC")
        self.age_cb_1.addItem("Intermediate-Code","IC")
        self.age_cb_1.addItem("Low-Code","LC")
        self.age_cb_1.addItem("No-Code", "NC")
        self.age_cb_1.setCurrentIndex(0)
        self.age_cb_1.view().setFixedWidth(250)
        
        # Number of stories for left image label
        self.n_stories_1 = QtWidgets.QLabel(self.centralwidget)
        self.n_stories_1.setGeometry(QtCore.QRect(20, 630, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.n_stories_1.setFont(font)
        self.n_stories_1.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.n_stories_1.setObjectName("n_stories_1")
        # Number of stories value
        self.n_stories_value_1 = QtWidgets.QComboBox(self.centralwidget)
        self.n_stories_value_1.setGeometry(QtCore.QRect(170, 630, 241, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.n_stories_value_1.setFont(font)
        self.n_stories_value_1.setObjectName("n_stories_value_1")
        self.n_stories_value_1.addItem("Select Number of Stories")
        self.n_stories_value_1.addItem("1", "1")
        self.n_stories_value_1.addItem("2", "2")
        self.n_stories_value_1.addItem("3", "3")
        self.n_stories_value_1.addItem("4", "4")
        self.n_stories_value_1.addItem("5", "5")
        self.n_stories_value_1.addItem("6-7", "6.0-7.0")
        self.n_stories_value_1.addItem("8-9", "8.0-9.0")
        self.n_stories_value_1.addItem("10-12", "10.0-12.0")
        self.n_stories_value_1.addItem("13+","13+")
        self.n_stories_value_1.setCurrentIndex(0)
        self.n_stories_value_1.view().setFixedWidth(250)
        
        # Occupacy type for left image label
        self.occupancy = QtWidgets.QLabel(self.centralwidget)
        self.occupancy.setGeometry(QtCore.QRect(20, 670, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.occupancy.setFont(font)
        self.occupancy.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.occupancy.setObjectName("occupancy")
        # Occupancy Combobox elements
        self.occup_cb_1 = QtWidgets.QComboBox(self.centralwidget)
        self.occup_cb_1.setGeometry(QtCore.QRect(170, 670, 241, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.occup_cb_1.setFont(font)
        self.occup_cb_1.setObjectName("occup_cb_1")
        self.occup_cb_1.addItem("Select Occupancy")
        self.occup_cb_1.addItem("Residential", "RES")
        self.occup_cb_1.addItem("Commercial","COM")
        self.occup_cb_1.addItem("Mixed","MIX")
        self.occup_cb_1.addItem("Educational","EDU")
        self.occup_cb_1.addItem("Government", "GOV")
        self.occup_cb_1.addItem("Industrial","IND")
        self.occup_cb_1.addItem("Other","OCO")
        self.occup_cb_1.setCurrentIndex(0)
        self.occup_cb_1.view().setFixedWidth(250)
        
        # Block position for left image label
        self.block_position = QtWidgets.QLabel(self.centralwidget)
        self.block_position.setGeometry(QtCore.QRect(20, 710, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.block_position.setFont(font)
        self.block_position.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.block_position.setObjectName("block_position")
        # Block position Combobox elements
        self.bck_pos_cb_1 = QtWidgets.QComboBox(self.centralwidget)
        self.bck_pos_cb_1.setGeometry(QtCore.QRect(170, 710, 241, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.bck_pos_cb_1.setFont(font)
        self.bck_pos_cb_1.setObjectName("bck_pos_cb_1")
        self.bck_pos_cb_1.addItem("Select Block Position")
        self.bck_pos_cb_1.addItem("Detached building", "BDP")
        self.bck_pos_cb_1.addItem("Adjoining building(s) one side", "BP1")
        self.bck_pos_cb_1.addItem("Adjoining building(s) two side", "BP2")
        self.bck_pos_cb_1.addItem("Adjoining building(s) three side", "BP3")
        self.bck_pos_cb_1.setCurrentIndex(0)
        self.bck_pos_cb_1.view().setFixedWidth(250)
        
        # Image quality for left image label
        self.img_quality = QtWidgets.QLabel(self.frame_left_img)
        self.img_quality.setGeometry(QtCore.QRect(10, 600, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.img_quality.setFont(font)
        self.img_quality.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.img_quality.setObjectName("img_quality")
        # Image quality Combobox elements      
        self.img_q_cb_1 = QtWidgets.QComboBox(self.centralwidget)
        self.img_q_cb_1.setGeometry(QtCore.QRect(170, 750, 241, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.img_q_cb_1.setFont(font)
        self.img_q_cb_1.setObjectName("img_q_cb_1")
        self.img_q_cb_1.addItem("Select Image quality")
        self.img_q_cb_1.addItem("Excellent", "Excellent")
        self.img_q_cb_1.addItem("Good","Good")
        self.img_q_cb_1.addItem("Intermediate","Intermediate")
        self.img_q_cb_1.addItem("Bad","Bad")
        self.img_q_cb_1.setCurrentIndex(0)
        self.img_q_cb_1.view().setFixedWidth(250)
        
       
        """ Central Building images elements """
        # Central image color frame
        self.frame_central_img = QtWidgets.QFrame(self.centralwidget)
        self.frame_central_img.setGeometry(QtCore.QRect(530, 150, 511, 641))
        self.frame_central_img.setStyleSheet("background-color: rgb(255, 170, 127)")
        self.frame_central_img.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_central_img.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_central_img.setObjectName("frame_central_img")
        # Elements for display central image or error message
        self.img_id_label_2 = QtWidgets.QLabel(self.frame_central_img)
        self.img_id_label_2.setGeometry(QtCore.QRect(10, 10, 131, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.img_id_label_2.setFont(font)
        self.img_id_label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.img_id_label_2.setObjectName("img_id_label_2")
        # Central image widget for best performance
        self.verticalLayoutWidget = QtWidgets.QWidget(self.frame_central_img)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 40, 491, 311))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        # Central image bounding box
        self.central_gsv_bb = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.central_gsv_bb.setContentsMargins(0, 0, 0, 0)
        self.central_gsv_bb.setObjectName("central_gsv_bb")
        # Central building image
        self.central_gsv_img = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.central_gsv_img.setText("")
        self.central_gsv_img.setObjectName("central_gsv_img")
        self.central_gsv_bb.addWidget(self.central_gsv_img)
        # Image ID for central frame
        self.img_id_value_2 = QtWidgets.QLineEdit(self.frame_central_img)
        self.img_id_value_2.setGeometry(QtCore.QRect(130, 10, 111, 21))
        self.img_id_value_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.img_id_value_2.setObjectName("img_id_value_2")
        # Bounding box for image central frame
        self.bounding_box_2 = QtWidgets.QPushButton(self.centralwidget)
        self.bounding_box_2.setGeometry(QtCore.QRect(830, 160, 161, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.bounding_box_2.setFont(font)
        self.bounding_box_2.setObjectName("bounding_box_2")
        
        ################## Form for building feature ##########################
        # Material for central image label 
        self.material_2 = QtWidgets.QLabel(self.centralwidget)
        self.material_2.setGeometry(QtCore.QRect(540, 510, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.material_2.setFont(font)
        self.material_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.material_2.setObjectName("material_2")
        # Material Combobox elements
        self.material_cb_2 = QtWidgets.QComboBox(self.centralwidget)
        self.material_cb_2.setGeometry(QtCore.QRect(690, 510, 241, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.material_cb_2.setFont(font)
        self.material_cb_2.setObjectName("material_cb_2")
        self.material_cb_2.addItem("Select Material")
        self.material_cb_2.addItem("Adobe-Earth-Stone","AES")
        self.material_cb_2.addItem("Concrete", "CR")
        self.material_cb_2.addItem("Masonry - Confined","MCF")
        self.material_cb_2.addItem("Masonry - Reinforced","MR")
        self.material_cb_2.addItem("Masonry - Unreinforced","MUR")
        self.material_cb_2.addItem("Steel","S")
        self.material_cb_2.addItem("Other","MATO")
        self.material_cb_2.setCurrentIndex(0)
        self.material_cb_2.view().setFixedWidth(250)
        
        # LLRS Ccentral image label
        self.llrs_2 = QtWidgets.QLabel(self.centralwidget)
        self.llrs_2.setGeometry(QtCore.QRect(540, 549, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.llrs_2.setFont(font)
        self.llrs_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.llrs_2.setObjectName("llrs_2")
        # LLRS Combobox elements
        self.llrs_cb_2 = QtWidgets.QComboBox(self.centralwidget)
        self.llrs_cb_2.setGeometry(QtCore.QRect(690, 551, 241, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.llrs_cb_2.setFont(font)
        self.llrs_cb_2.setObjectName("llrs_cb_2")
        self.llrs_cb_2.addItem("Select LLRS")
        self.llrs_cb_2.addItem("Dual System","LDUAL")
        self.llrs_cb_2.addItem("Infilled Frames", "LFINF")
        self.llrs_cb_2.addItem("Moment Frames", "LFM")
        self.llrs_cb_2.addItem("Walls","LWAL")
        self.llrs_cb_2.addItem("Thin Wall","TW")
        self.llrs_cb_2.addItem("Other","O")
        self.llrs_cb_2.setCurrentIndex(0)
        self.llrs_cb_2.view().setFixedWidth(250)
        
        # Code level for central image
        self.age_2 = QtWidgets.QLabel(self.frame_central_img)
        self.age_2.setGeometry(QtCore.QRect(10, 440, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.age_2.setFont(font)
        self.age_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.age_2.setObjectName("age_2")
        # Code level Combobox elements
        self.age_cb_2 = QtWidgets.QComboBox(self.centralwidget)
        self.age_cb_2.setGeometry(QtCore.QRect(690, 590, 241, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.age_cb_2.setFont(font)
        self.age_cb_2.setObjectName("age_cb_2")
        self.age_cb_2.addItem("Select Code Level")
        self.age_cb_2.addItem("High-Code","HC")
        self.age_cb_2.addItem("Intermediate-Code","IC")
        self.age_cb_2.addItem("Low-Code","LC")
        self.age_cb_2.addItem("No-Code", "NC")
        self.age_cb_2.setCurrentIndex(0)
        self.age_cb_2.view().setFixedWidth(250)
        
        # Number of stories elements
        self.n_stories_2 = QtWidgets.QLabel(self.centralwidget)
        self.n_stories_2.setGeometry(QtCore.QRect(540, 630, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.n_stories_2.setFont(font)
        self.n_stories_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.n_stories_2.setObjectName("n_stories_2")
        # Number of stories value
        self.n_stories_value_2 = QtWidgets.QComboBox(self.centralwidget)
        self.n_stories_value_2.setGeometry(QtCore.QRect(690, 630, 241, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.n_stories_value_2.setFont(font)
        self.n_stories_value_2.setObjectName("n_stories_value_2")
        self.n_stories_value_2.addItem("Select Number of Stories")
        self.n_stories_value_2.addItem("1", "1")
        self.n_stories_value_2.addItem("2", "2")
        self.n_stories_value_2.addItem("3", "3")
        self.n_stories_value_2.addItem("4", "4")
        self.n_stories_value_2.addItem("5", "5")
        self.n_stories_value_2.addItem("6-7", "6.0-7.0")
        self.n_stories_value_2.addItem("8-9", "8.0-9.0")
        self.n_stories_value_2.addItem("10-12", "10.0-12.0")
        self.n_stories_value_2.addItem("13+","13+")
        self.n_stories_value_2.setCurrentIndex(0)
        self.n_stories_value_2.view().setFixedWidth(250)
        
        # Occupancy type label
        self.occupancy_2 = QtWidgets.QLabel(self.centralwidget)
        self.occupancy_2.setGeometry(QtCore.QRect(540, 670, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.occupancy_2.setFont(font)
        self.occupancy_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.occupancy_2.setObjectName("occupancy_2")
        # Occupancy type Combobox elements
        self.occup_cb_2 = QtWidgets.QComboBox(self.centralwidget)
        self.occup_cb_2.setGeometry(QtCore.QRect(690, 670, 241, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.occup_cb_2.setFont(font)
        self.occup_cb_2.setObjectName("occup_cb_2")
        self.occup_cb_2.addItem("Select Occupancy")
        self.occup_cb_2.addItem("Residential", "RES")
        self.occup_cb_2.addItem("Commercial","COM")
        self.occup_cb_2.addItem("Mixed","MIX")
        self.occup_cb_2.addItem("Educational","EDU")
        self.occup_cb_2.addItem("Government", "GOV")
        self.occup_cb_2.addItem("Industrial","IND")
        self.occup_cb_2.addItem("Other","OCO")
        self.occup_cb_2.setCurrentIndex(0)
        self.occup_cb_2.view().setFixedWidth(250)
       
        # Block position Combobox elements
        self.block_position_2 = QtWidgets.QLabel(self.centralwidget)
        self.block_position_2.setGeometry(QtCore.QRect(540, 710, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.block_position_2.setFont(font)
        self.block_position_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.block_position_2.setObjectName("block_position_2")
        # Block Position Combobox elements
        self.bck_pos_cb_2 = QtWidgets.QComboBox(self.centralwidget)
        self.bck_pos_cb_2.setGeometry(QtCore.QRect(690, 710, 241, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.bck_pos_cb_2.setFont(font)
        self.bck_pos_cb_2.setObjectName("bck_pos_cb_2")
        self.bck_pos_cb_2.addItem("Select Block Position")
        self.bck_pos_cb_2.addItem("Detached building", "BDP")
        self.bck_pos_cb_2.addItem("Adjoining building(s) one side", "BP1")
        self.bck_pos_cb_2.addItem("Adjoining building(s) two side", "BP2")
        self.bck_pos_cb_2.addItem("Adjoining building(s) three side", "BP3")
        self.bck_pos_cb_2.setCurrentIndex(0)
        self.bck_pos_cb_2.view().setFixedWidth(250)
        
        # Image quality for central image
        self.img_quality_2 = QtWidgets.QLabel(self.frame_central_img)
        self.img_quality_2.setGeometry(QtCore.QRect(10, 600, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.img_quality_2.setFont(font)
        self.img_quality_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.img_quality_2.setObjectName("img_quality_2")
        # Image quality Combobox elements
        self.img_q_cb_2 = QtWidgets.QComboBox(self.centralwidget)
        self.img_q_cb_2.setGeometry(QtCore.QRect(690, 750, 241, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.img_q_cb_2.setFont(font)
        self.img_q_cb_2.setObjectName("img_q_cb_2")
        self.img_q_cb_2.addItem("Select Image quality")
        self.img_q_cb_2.addItem("Excellent", "Excellent")
        self.img_q_cb_2.addItem("Good","Good")
        self.img_q_cb_2.addItem("Intermediate","Intermediate")
        self.img_q_cb_2.addItem("Bad","Bad")
        self.img_q_cb_2.setCurrentIndex(0)
        self.img_q_cb_2.view().setFixedWidth(250)
        
        
        """ Right Building images elements """
        # Right image color frame
        self.frame_right_img = QtWidgets.QFrame(self.centralwidget)
        self.frame_right_img.setGeometry(QtCore.QRect(1050, 150, 511, 641))
        self.frame_right_img.setStyleSheet("background-color: rgb(183, 252, 172)")
        self.frame_right_img.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_right_img.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_right_img.setObjectName("frame_right_img")
        self.img_id_label_3 = QtWidgets.QLabel(self.frame_right_img)
        self.img_id_label_3.setGeometry(QtCore.QRect(10, 10, 131, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        # Elements for display right image or error message
        self.img_id_label_3.setFont(font)
        self.img_id_label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.img_id_label_3.setObjectName("img_id_label_3")
        # Right image widget for best performance
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.frame_right_img)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(10, 39, 491, 311))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        # Right image bounding box
        self.right_gsv_bb = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.right_gsv_bb.setContentsMargins(0, 0, 0, 0)
        self.right_gsv_bb.setObjectName("right_gsv_bb")
        # Right building image
        self.right_gsv_img = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.right_gsv_img.setText("")
        self.right_gsv_img.setObjectName("right_gsv_img")
        self.right_gsv_bb.addWidget(self.right_gsv_img)
        # Image ID for right frame
        self.img_id_value_3 = QtWidgets.QLineEdit(self.frame_right_img)
        self.img_id_value_3.setGeometry(QtCore.QRect(150, 10, 111, 21))
        self.img_id_value_3.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.img_id_value_3.setObjectName("img_id_value_3")
        # Bounding box for image right frame
        self.bounding_box_3 = QtWidgets.QPushButton(self.centralwidget)
        self.bounding_box_3.setGeometry(QtCore.QRect(1360, 160, 161, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.bounding_box_3.setFont(font)
        self.bounding_box_3.setObjectName("bounding_box_3")
        
        ################## Form for building feature ##########################
        
        # Material for right image label
        self.material_3 = QtWidgets.QLabel(self.centralwidget)
        self.material_3.setGeometry(QtCore.QRect(1060, 510, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.material_3.setFont(font)
        self.material_3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.material_3.setObjectName("material_3")
        # Material right combobox elements
        self.material_cb_3 = QtWidgets.QComboBox(self.centralwidget)
        self.material_cb_3.setGeometry(QtCore.QRect(1210, 510, 241, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.material_cb_3.setFont(font)
        self.material_cb_3.setObjectName("material_cb_3")
        self.material_cb_3.addItem("Select Material")
        self.material_cb_3.addItem("Adobe-Earth-Stone","AES")
        self.material_cb_3.addItem("Concrete", "CR")
        self.material_cb_3.addItem("Masonry - Confined","MCF")
        self.material_cb_3.addItem("Masonry - Reinforced","MR")
        self.material_cb_3.addItem("Masonry - Unreinforced","MUR")
        self.material_cb_3.addItem("Steel","S")
        self.material_cb_3.addItem("Other","MATO")
        self.material_cb_3.setCurrentIndex(0)
        self.material_cb_3.view().setFixedWidth(250)
        
        # LLRS for right image label
        self.llrs_3 = QtWidgets.QLabel(self.centralwidget)
        self.llrs_3.setGeometry(QtCore.QRect(1060, 549, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.llrs_3.setFont(font)
        self.llrs_3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.llrs_3.setObjectName("llrs_3")
        # LLRS right combobox elements
        self.llrs_cb_3 = QtWidgets.QComboBox(self.centralwidget)
        self.llrs_cb_3.setGeometry(QtCore.QRect(1210, 551, 241, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.llrs_cb_3.setFont(font)
        self.llrs_cb_3.setObjectName("llrs_cb_3")
        self.llrs_cb_3.addItem("Select LLRS")
        self.llrs_cb_3.addItem("Dual System","LDUAL")
        self.llrs_cb_3.addItem("Infilled Frames", "LFINF")
        self.llrs_cb_3.addItem("Moment Frames", "LFM")
        self.llrs_cb_3.addItem("Walls","LWAL")
        self.llrs_cb_3.addItem("Thin Wall","TW")
        self.llrs_cb_3.addItem("Other","O")
        self.llrs_cb_3.setCurrentIndex(0)
        self.llrs_cb_3.view().setFixedWidth(250)
        
        # Code level for right image label
        self.age_3 = QtWidgets.QLabel(self.centralwidget)
        self.age_3.setGeometry(QtCore.QRect(1060, 590, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.age_3.setFont(font)
        self.age_3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.age_3.setObjectName("age_3")
        # Code level right combobox elements
        self.age_cb_3 = QtWidgets.QComboBox(self.centralwidget)
        self.age_cb_3.setGeometry(QtCore.QRect(1210, 590, 241, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.age_cb_3.setFont(font)
        self.age_cb_3.setObjectName("age_cb_3")
        self.age_cb_3.addItem("Select Code Level")
        self.age_cb_3.addItem("High-Code","HC")
        self.age_cb_3.addItem("Intermediate-Code","IC")
        self.age_cb_3.addItem("Low-Code","LC")
        self.age_cb_3.addItem("No-Code", "NC")
        self.age_cb_3.setCurrentIndex(0)
        self.age_cb_3.view().setFixedWidth(250)
        
        # Number of stories for right image label
        self.n_stories_3 = QtWidgets.QLabel(self.centralwidget)
        self.n_stories_3.setGeometry(QtCore.QRect(1060, 630, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.n_stories_3.setFont(font)
        self.n_stories_3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.n_stories_3.setObjectName("n_stories_3")
        # Number of stories value
        self.n_stories_value_3 = QtWidgets.QComboBox(self.centralwidget)
        self.n_stories_value_3.setGeometry(QtCore.QRect(1210, 630, 241, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.n_stories_value_3.setFont(font)
        self.n_stories_value_3.setObjectName("n_stories_value_3")
        self.n_stories_value_3.addItem("Select Number of Stories")
        self.n_stories_value_3.addItem("1", "1")
        self.n_stories_value_3.addItem("2", "2")
        self.n_stories_value_3.addItem("3", "3")
        self.n_stories_value_3.addItem("4", "4")
        self.n_stories_value_3.addItem("5", "5")
        self.n_stories_value_3.addItem("6-7", "6.0-7.0")
        self.n_stories_value_3.addItem("8-9", "8.0-9.0")
        self.n_stories_value_3.addItem("10-12", "10.0-12.0")
        self.n_stories_value_3.addItem("13+","13+")
        self.n_stories_value_3.setCurrentIndex(0)
        self.n_stories_value_3.view().setFixedWidth(250)
        
        # Occupancy type for right image label
        self.occupancy_3 = QtWidgets.QLabel(self.centralwidget)
        self.occupancy_3.setGeometry(QtCore.QRect(1060, 670, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.occupancy_3.setFont(font)
        self.occupancy_3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.occupancy_3.setObjectName("occupancy_3")
        # Occupacy type right combobox elements
        self.occup_cb_3 = QtWidgets.QComboBox(self.centralwidget)
        self.occup_cb_3.setGeometry(QtCore.QRect(1210, 670, 241, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.occup_cb_3.setFont(font)
        self.occup_cb_3.setObjectName("occup_cb_3")
        self.occup_cb_3.addItem("Select Occupancy")
        self.occup_cb_3.addItem("Residential", "RES")
        self.occup_cb_3.addItem("Commercial","COM")
        self.occup_cb_3.addItem("Mixed","MIX")
        self.occup_cb_3.addItem("Educational","EDU")
        self.occup_cb_3.addItem("Government", "GOV")
        self.occup_cb_3.addItem("Industrial","IND")
        self.occup_cb_3.addItem("Other","OCO")
        self.occup_cb_3.setCurrentIndex(0)
        self.occup_cb_3.view().setFixedWidth(250)
                     
        # Block position for right image label
        self.block_position_3 = QtWidgets.QLabel(self.centralwidget)
        self.block_position_3.setGeometry(QtCore.QRect(1060, 710, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.block_position_3.setFont(font)
        self.block_position_3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.block_position_3.setObjectName("block_position_3")
        # Block position right combobox elements
        self.bck_pos_cb_3 = QtWidgets.QComboBox(self.centralwidget)
        self.bck_pos_cb_3.setGeometry(QtCore.QRect(1210, 710, 241, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.bck_pos_cb_3.setFont(font)
        self.bck_pos_cb_3.setObjectName("bck_pos_cb_3")
        self.bck_pos_cb_3.addItem("Select Block Position")
        self.bck_pos_cb_3.addItem("Detached building", "BDP")
        self.bck_pos_cb_3.addItem("Adjoining building(s) one side", "BP1")
        self.bck_pos_cb_3.addItem("Adjoining building(s) two side", "BP2")
        self.bck_pos_cb_3.addItem("Adjoining building(s) three side", "BP3")
        self.bck_pos_cb_3.setCurrentIndex(0)
        self.bck_pos_cb_3.view().setFixedWidth(250)
        
        # Image quality for right image label
        self.img_quality_3 = QtWidgets.QLabel(self.frame_right_img)
        self.img_quality_3.setGeometry(QtCore.QRect(10, 600, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.img_quality_3.setFont(font)
        self.img_quality_3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.img_quality_3.setObjectName("img_quality_3")
        # Image quality right combobox elements
        self.img_q_cb_3 = QtWidgets.QComboBox(self.centralwidget)
        self.img_q_cb_3.setGeometry(QtCore.QRect(1210, 750, 241, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.img_q_cb_3.setFont(font)
        self.img_q_cb_3.setObjectName("img_q_cb_3")
        self.img_q_cb_3.addItem("Select Image quality")
        self.img_q_cb_3.addItem("Excellent", "Excellent")
        self.img_q_cb_3.addItem("Good","Good")
        self.img_q_cb_3.addItem("Intermediate","Intermediate")
        self.img_q_cb_3.addItem("Bad","Bad")
        self.img_q_cb_3.setCurrentIndex(0)
        self.img_q_cb_3.view().setFixedWidth(250)
        
###########################################################################################        
###########################################################################################   
        
        """ Search button elements """
        self.search_img_button = QtWidgets.QPushButton(self.centralwidget)
        self.search_img_button.setGeometry(QtCore.QRect(1400, 800, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.search_img_button.setFont(font)
        self.search_img_button.setObjectName("search_img_button")
        self.search_img_value = QtWidgets.QLineEdit(self.centralwidget)
        self.search_img_value.setPlaceholderText("Enter image ID to search")
        self.search_img_value.setGeometry(QtCore.QRect(1250, 800, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.search_img_value.setFont(font)
        self.search_img_value.setObjectName("search_img_value")
        self.search_img_label = QtWidgets.QLabel(self.centralwidget)
        self.search_img_label.setGeometry(QtCore.QRect(1140, 800, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.search_img_label.setFont(font)
        self.search_img_label.setAlignment(QtCore.Qt.AlignCenter)
        self.search_img_label.setObjectName("search_img_label")
        
        
        """ GEM Logo elements """
        self.GEM_logo = QtWidgets.QLabel(self.centralwidget)
        self.GEM_logo.setGeometry(QtCore.QRect(1320, 10, 241, 51))
        self.GEM_logo.setText("")
        self.GEM_logo.setPixmap(QtGui.QPixmap("GEM_Logo.png"))
        self.GEM_logo.setScaledContents(True)
        self.GEM_logo.setObjectName("GEM_logo")
        
        
        """ GEM icon GUI elements """
        self.setWindowIcon(QtGui.QIcon("GEM_icon.ico"))
        
        
        """ Porgress Bar elements """
        # Progress bar widget
        self.progress_bar_method = QtWidgets.QProgressBar(self.centralwidget)
        self.progress_bar_method.setGeometry(QtCore.QRect(620, 830, 161, 23))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.progress_bar_method.setFont(font)
        self.progress_bar_method.setProperty("value", 0)
        self.progress_bar_method.setObjectName("progress_bar_method")
        # Progress bar label value
        self.method_progress = QtWidgets.QLabel(self.centralwidget)
        self.method_progress.setGeometry(QtCore.QRect(800, 820, 291, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.method_progress.setFont(font)
        self.method_progress.setObjectName("method_progress")
        
        
        """ Coordinates input by file button elements """
        # Button set coordinates
        self.set_cood_button = QtWidgets.QPushButton(self.centralwidget)
        self.set_cood_button.setGeometry(QtCore.QRect(500, 90, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.set_cood_button.setFont(font)
        self.set_cood_button.setObjectName("set_cood_button")
        # Colored frame area
        self.frame_coord_val = QtWidgets.QFrame(self.centralwidget)
        self.frame_coord_val.setGeometry(QtCore.QRect(650, 40, 391, 91))
        self.frame_coord_val.setStyleSheet("background-color: rgb(254, 255, 174);")
        self.frame_coord_val.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_coord_val.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_coord_val.setObjectName("frame_coord_val")
        
        
        """ Method  button elements """
        # Button set method
        self.method_button = QtWidgets.QPushButton(self.centralwidget)
        self.method_button.setGeometry(QtCore.QRect(500, 50, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.method_button.setFont(font)
        self.method_button.setObjectName("method_button")
        
       
        """ AI Powered activation elements """
        # AI checkbox activation
        self.ai_check = QtWidgets.QCheckBox(self.centralwidget)
        self.ai_check.setGeometry(QtCore.QRect(400, 830, 131, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.ai_check.setFont(font)
        self.ai_check.setObjectName("ai_check")
        
      
        """ Save data button elements """ 
        # Saved data button
        self.save_data_button = QtWidgets.QPushButton(self.centralwidget)
        self.save_data_button.setGeometry(QtCore.QRect(1140, 840, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.save_data_button.setFont(font)
        self.save_data_button.setObjectName("save_data_button")
        
        
        """ Raise all elements """
        self.frame_coord_val.raise_()
        self.frame_location.raise_()
        self.path_out_folder_bt.raise_()
        self.country_label_input.raise_()
        self.city_label.raise_()
        self.Tittle.raise_()
        self.output_folder_value.raise_()
        self.output_path_tittle.raise_()
        self.lat_label.raise_()
        self.lon_label.raise_()
        self.previous_button.raise_()
        self.lat_value.raise_()
        self.lon_value.raise_()
        self.country_value.raise_()
        self.city_value.raise_()
        self.frame_central_img.raise_()
        self.frame_right_img.raise_()
        self.frame_left_img.raise_()
        self.material_1.raise_()
        self.llrs_1.raise_()
        self.age_1.raise_()
        self.n_stories_1.raise_()
        self.occupancy.raise_()
        self.block_position.raise_()
        self.next_button.raise_()
        self.material_cb_1.raise_()
        self.llrs_cb_1.raise_()
        self.age_cb_1.raise_()
        self.occup_cb_1.raise_()
        self.bck_pos_cb_1.raise_()
        self.img_q_cb_1.raise_()
        self.search_img_button.raise_()
        self.search_img_value.raise_()
        self.search_img_label.raise_()
        self.GEM_logo.raise_()
        self.material_cb_2.raise_()
        self.llrs_cb_2.raise_()
        self.img_q_cb_2.raise_()
        self.age_cb_2.raise_()
        self.bck_pos_cb_2.raise_()
        self.n_stories_2.raise_()
        self.occup_cb_2.raise_()
        self.block_position_2.raise_()
        self.material_2.raise_()
        self.llrs_2.raise_()
        self.occupancy_2.raise_()
        self.material_cb_3.raise_()
        self.llrs_cb_3.raise_()
        self.img_q_cb_3.raise_()
        self.age_cb_3.raise_()
        self.bck_pos_cb_3.raise_()
        self.n_stories_3.raise_()
        self.occup_cb_3.raise_()
        self.block_position_3.raise_()
        self.material_3.raise_()
        self.llrs_3.raise_()
        self.age_3.raise_()
        self.occupancy_3.raise_()
        self.progress_bar_method.raise_()
        self.method_progress.raise_()
        self.set_cood_button.raise_()
        self.ai_check.raise_()
        self.save_data_button.raise_()
        self.method_button.raise_()
        self.n_stories_value_1.raise_()
        self.n_stories_value_2.raise_()
        self.n_stories_value_3.raise_()
        self.bounding_box_1.raise_()
        self.bounding_box_2.raise_()
        self.bounding_box_3.raise_()
        GUIInterface.setCentralWidget(self.centralwidget)

        self.retranslateUi(GUIInterface)
        QtCore.QMetaObject.connectSlotsByName(GUIInterface)
        
    
        """ Method for translation """
    def retranslateUi(self, GUIInterface):
        _translate = QtCore.QCoreApplication.translate
        GUIInterface.setWindowTitle(_translate("GUIInterface", "GEM Data Collection"))
        self.path_out_folder_bt.setText(_translate("GUIInterface", "Project Folder"))
        self.country_label_input.setText(_translate("GUIInterface", "Country:"))
        self.city_label.setText(_translate("GUIInterface", "City:"))
        self.Tittle.setText(_translate("GUIInterface", "Building Feature Collection"))
        self.output_folder_value.setText(_translate("GUIInterface", "-"))
        self.output_path_tittle.setText(_translate("GUIInterface", "Project Selection"))
        self.lat_label.setText(_translate("GUIInterface", "Building Latitude: "))
        self.lon_label.setText(_translate("GUIInterface", "Building Longitude:"))
        self.previous_button.setText(_translate("GUIInterface", "Previous Building"))
        self.lat_value.setText(_translate("GUIInterface", "-"))
        self.lon_value.setText(_translate("GUIInterface", "-"))
        self.country_value.setText(_translate("GUIInterface", "-"))
        self.city_value.setText(_translate("GUIInterface", "-"))
        self.img_id_label_2.setText(_translate("GUIInterface", "Image ID:"))
        self.img_id_value_2.setText(_translate("GUIInterface", "-"))
        self.img_quality_2.setText(_translate("GUIInterface", "Image Quality:"))
        self.age_2.setText(_translate("GUIInterface", "Code Level:"))
        self.img_id_label_3.setText(_translate("GUIInterface", "Image ID:"))
        self.img_id_value_3.setText(_translate("GUIInterface", "-"))
        self.img_quality_3.setText(_translate("GUIInterface", "Image Quality:"))
        self.img_id_label_1.setText(_translate("GUIInterface", "Image ID:"))
        self.img_id_value_1.setText(_translate("GUIInterface", "-"))
        self.img_quality.setText(_translate("GUIInterface", "Image Quality:"))
        self.material_1.setText(_translate("GUIInterface", "LLRS Material:"))
        self.llrs_1.setText(_translate("GUIInterface", "LLRS:"))
        self.age_1.setText(_translate("GUIInterface", "Code Level:"))
        self.n_stories_1.setText(_translate("GUIInterface", "N° of Stories:"))
        self.occupancy.setText(_translate("GUIInterface", "Occupancy:"))
        self.block_position.setText(_translate("GUIInterface", "Block Position:"))
        self.next_button.setText(_translate("GUIInterface", "Next Building"))
        self.material_cb_1.setItemText(0, _translate("GUIInterface", "Select Material"))
        self.llrs_cb_1.setItemText(0, _translate("GUIInterface", "Select LLRS"))
        self.age_cb_1.setItemText(0, _translate("GUIInterface", "Select Code Level"))
        self.occup_cb_1.setItemText(0, _translate("GUIInterface", "Select Occupancy Type"))
        self.bck_pos_cb_1.setItemText(0, _translate("GUIInterface", "Select Block Position"))
        self.img_q_cb_1.setItemText(0, _translate("GUIInterface", "Select Image Quality"))
        self.search_img_button.setText(_translate("GUIInterface", "Search Building"))
        self.search_img_label.setText(_translate("GUIInterface", "Image ID:"))
        self.location_label.setText(_translate("GUIInterface", "Location"))
        self.material_cb_2.setItemText(0, _translate("GUIInterface", "Select Material"))
        self.llrs_cb_2.setItemText(0, _translate("GUIInterface", "Select LLRS"))
        self.img_q_cb_2.setItemText(0, _translate("GUIInterface", "Select Image Quality"))
        self.age_cb_2.setItemText(0, _translate("GUIInterface", "Select Code Level"))
        self.bck_pos_cb_2.setItemText(0, _translate("GUIInterface", "Select Block Position"))
        self.n_stories_2.setText(_translate("GUIInterface", "N° of Stories:"))
        self.occup_cb_2.setItemText(0, _translate("GUIInterface", "Select Occupancy Type"))
        self.block_position_2.setText(_translate("GUIInterface", "Block Position:"))
        self.material_2.setText(_translate("GUIInterface", "LLRS Material:"))
        self.llrs_2.setText(_translate("GUIInterface", "LLRS:"))
        self.occupancy_2.setText(_translate("GUIInterface", "Occupancy:"))
        self.material_cb_3.setItemText(0, _translate("GUIInterface", "Select Material"))
        self.llrs_cb_3.setItemText(0, _translate("GUIInterface", "Select LLRS"))
        self.img_q_cb_3.setItemText(0, _translate("GUIInterface", "Select Image Quality"))
        self.age_cb_3.setItemText(0, _translate("GUIInterface", "Select Code Level"))
        self.bck_pos_cb_3.setItemText(0, _translate("GUIInterface", "Select Block Position"))
        self.n_stories_3.setText(_translate("GUIInterface", "N° of Stories:"))
        self.occup_cb_3.setItemText(0, _translate("GUIInterface", "Select Occupancy Type"))
        self.block_position_3.setText(_translate("GUIInterface", "Block Position:"))
        self.material_3.setText(_translate("GUIInterface", "LLRS Material:"))
        self.llrs_3.setText(_translate("GUIInterface", "LLRS:"))
        self.age_3.setText(_translate("GUIInterface", "Code Level:"))
        self.occupancy_3.setText(_translate("GUIInterface", "Occupancy:"))
        self.method_progress.setText(_translate("GUIInterface", "-"))
        self.set_cood_button.setText(_translate("GUIInterface", "Set Coord."))
        self.ai_check.setText(_translate("GUIInterface", "AI Powered"))
        self.save_data_button.setText(_translate("GUIInterface", "Save data"))
        self.method_button.setText(_translate("GUIInterface", "Insp. Method"))
        self.bounding_box_1.setText(_translate("search_img_value", "Manual box"))
        self.bounding_box_2.setText(_translate("search_img_value", "Manual box"))
        self.bounding_box_3.setText(_translate("search_img_value", "Manual box"))